//! Compress / uncompress Tachibana Securities API JSON keys.
//!
//! The API uses numeric 1-indexed keys in transit (e.g. `"334"` → `"sCLMID"`).
//! The mapping is derived from `mfds_json_api_compress_v4r8.js`.

use serde_json::{Map, Value};

/// 941 column names sorted alphabetically (same order as the JS compress table).
/// Index 0 corresponds to wire key `"1"`, index 1 → `"2"`, etc.
const COLUMNS: &[&str] = &[
    "CLMAuthApiKeyEncryptAck",
    "CLMAuthApiKeyEncryptRequest",
    "CLMAuthCheckSecondPassword",
    "CLMAuthLoginAck",
    "CLMAuthLoginRequest",
    "CLMAuthLogoutAck",
    "CLMAuthLogoutRequest",
    "CLMAuthSessionInfo",
    "CLMAuthStkLoginRequest",
    "CLMDaiyouKakeme",
    "CLMDateZyouhou",
    "CLMEventDownload",
    "CLMEventDownloadComplete",
    "CLMGenbutuKabuList",
    "CLMHosyoukinMst",
    "CLMIssueMstKabu",
    "CLMIssueMstOp",
    "CLMIssueMstOther",
    "CLMIssueMstSak",
    "CLMIssueSizyouKiseiHasei",
    "CLMIssueSizyouKiseiKabu",
    "CLMIssueSizyouMstKabu",
    "CLMKabuCancelOrder",
    "CLMKabuCorrectOrder",
    "CLMKabuNewOrder",
    "CLMKabuOrderUpdateEvent",
    "CLMKeepAliveRequest",
    "CLMMfdsEventData",
    "CLMMfdsGetEventData",
    "CLMMfdsGetEventNoLast",
    "CLMMfdsGetHibuInfo",
    "CLMMfdsGetIssueDetail",
    "CLMMfdsGetMarketPriceHistory",
    "CLMMfdsGetMarketPriceTick",
    "CLMMfdsGetMarketRank",
    "CLMMfdsGetMasterData",
    "CLMMfdsGetNewsBody",
    "CLMMfdsGetNewsHead",
    "CLMMfdsGetShinyouZan",
    "CLMMfdsGetSyoukinZan",
    "CLMMsgTable",
    "CLMNyuukinKouzaInfo",
    "CLMOrderErrReason",
    "CLMOrderList",
    "CLMOrderListDetail",
    "CLMShinyouTategyokuList",
    "CLMSystemStatus",
    "CLMSyukkinInfo",
    "CLMSyukkinSiji",
    "CLMSyukkinTorikesiInfo",
    "CLMSyukkinTorikesiSiji",
    "CLMUnyouStatus",
    "CLMUnyouStatusHasei",
    "CLMUnyouStatusKabu",
    "CLMYobine",
    "CLMZanKaiGenbutuKaitukeSyousai",
    "CLMZanKaiKanougaku",
    "CLMZanKaiKanougakuSuii",
    "CLMZanKaiSinyouSinkidateSyousai",
    "CLMZanKaiSummary",
    "CLMZanRealHosyoukinRitu",
    "CLMZanShinkiKanoIjiritu",
    "CLMZanUriKanousuu",
    "aCLMKabuHensaiData",
    "aCLMMfdsEventData",
    "aCLMMfdsHibuInfo",
    "aCLMMfdsIssueDetail",
    "aCLMMfdsIssueElement",
    "aCLMMfdsIssueMaster",
    "aCLMMfdsKessan",
    "aCLMMfdsMarketPrice",
    "aCLMMfdsMarketPriceHistory",
    "aCLMMfdsMarketPriceTick",
    "aCLMMfdsMarketRank",
    "aCLMMfdsNewsBody",
    "aCLMMfdsNewsHead",
    "aCLMMfdsRchAlertSettingGet",
    "aCLMMfdsRchBoardGet",
    "aCLMMfdsRchBoardUpd",
    "aCLMMfdsRchLayoutLoad",
    "aCLMMfdsRchStorageLoad",
    "aCLMMfdsShinyouZan",
    "aCLMMfdsSihonIdou",
    "aCLMMfdsSyoukinZan",
    "aFncDataList",
    "aFncHolidayList",
    "aFncKensuuList",
    "aGenbutuKabuList",
    "aHikazeiKouzaList",
    "aHosyoukinSeikyuZyoukyouList",
    "aKanougakuSuiiList",
    "aKessaiOrderTategyokuList",
    "aOisyouHasseiZyoukyouList",
    "aOrderList",
    "aShinyouTategyokuList",
    "aYakuzyouSikkouList",
    "pAAV",
    "pABV",
    "pAV",
    "pBICD",
    "pBPSB",
    "pBV",
    "pBWRQ",
    "pCLOE",
    "pDHF",
    "pDHP",
    "pDHPxK",
    "pDJ",
    "pDLF",
    "pDLP",
    "pDLPxK",
    "pDOP",
    "pDOPxK",
    "pDPG",
    "pDPP",
    "pDPPxK",
    "pDV",
    "pDVxK",
    "pDYRP",
    "pDYWP",
    "pEPSF",
    "pEXRD",
    "pGAP1",
    "pGAP10",
    "pGAP2",
    "pGAP3",
    "pGAP4",
    "pGAP5",
    "pGAP6",
    "pGAP7",
    "pGAP8",
    "pGAP9",
    "pGAV1",
    "pGAV10",
    "pGAV2",
    "pGAV3",
    "pGAV4",
    "pGAV5",
    "pGAV6",
    "pGAV7",
    "pGAV8",
    "pGAV9",
    "pGBP1",
    "pGBP10",
    "pGBP2",
    "pGBP3",
    "pGBP4",
    "pGBP5",
    "pGBP6",
    "pGBP7",
    "pGBP8",
    "pGBP9",
    "pGBV1",
    "pGBV10",
    "pGBV2",
    "pGBV3",
    "pGBV4",
    "pGBV5",
    "pGBV6",
    "pGBV7",
    "pGBV8",
    "pGBV9",
    "pIDVE",
    "pISCD",
    "pMBB3",
    "pMBB6",
    "pMBBQ",
    "pMBC3",
    "pMBC6",
    "pMBCQ",
    "pMBD",
    "pMBN3",
    "pMBN6",
    "pMBNQ",
    "pMBR3",
    "pMBR6",
    "pMBRQ",
    "pMBS3",
    "pMBS6",
    "pMBSQ",
    "pPRP",
    "pQAP",
    "pQAS",
    "pQBP",
    "pQBS",
    "pQOV",
    "pQUV",
    "pRNO",
    "pROEL",
    "pRPER",
    "pRankType",
    "pReceiveDate",
    "pSFC6",
    "pSFD",
    "pSFD6",
    "pSFF6",
    "pSFG6",
    "pSFKS",
    "pSFL6",
    "pSFN6",
    "pSFP6",
    "pSFR6",
    "pSFS6",
    "pSPBR",
    "pSPRO",
    "pSPUC",
    "pSPUK",
    "pSPUO",
    "pSSG6",
    "pSSL6",
    "pSSP6",
    "pSYIE",
    "pVWAP",
    "pYHPD",
    "pYHPR",
    "pYLPD",
    "pYLPR",
    "p_ALT",
    "p_BBKB",
    "p_CG",
    "p_CGL",
    "p_CHNL",
    "p_CREPSR",
    "p_CREXSR",
    "p_CRPR",
    "p_CRPRKB",
    "p_CRSJ",
    "p_CRSR",
    "p_CRTKSR",
    "p_CT",
    "p_DT",
    "p_DT_FROM",
    "p_DT_TO",
    "p_ED",
    "p_EDK",
    "p_ENO",
    "p_EPRC",
    "p_EXDT",
    "p_EXPR",
    "p_EXRC",
    "p_EXSR",
    "p_EXST",
    "p_GNL",
    "p_GSCD",
    "p_HDL",
    "p_IC",
    "p_ID",
    "p_IN",
    "p_IS",
    "p_ISL",
    "p_JKK",
    "p_KEYWORD",
    "p_KOFG",
    "p_LK",
    "p_LMIT",
    "p_MC",
    "p_NT",
    "p_ODST",
    "p_ON",
    "p_OON",
    "p_OT",
    "p_PV",
    "p_REC_LIMT",
    "p_REC_MAX",
    "p_REC_OFST",
    "p_SHSB",
    "p_SS",
    "p_ST",
    "p_THKB",
    "p_TM",
    "p_TTST",
    "p_TX",
    "p_UC",
    "p_UPEXSR",
    "p_UPGKCDPR",
    "p_UPGKPR",
    "p_UPGKPRKB",
    "p_UPLMIT",
    "p_UPPR",
    "p_UPPRKB",
    "p_UPSJ",
    "p_UPSR",
    "p_US",
    "p_UU",
    "p_cmd",
    "p_err",
    "p_errno",
    "p_no",
    "p_rv_date",
    "p_sd_date",
    "rDPP",
    "rDPP:T",
    "rDYRP",
    "rDYWP",
    "rISCD",
    "rMBBQ",
    "rMBCQ",
    "rMBNQ",
    "rMBRQ",
    "rMBSQ",
    "rPBR",
    "rPER",
    "rRA05",
    "rRA25",
    "rRAR05",
    "rRAR25",
    "rRTDW",
    "rRTIK",
    "rRTUP",
    "rRV05",
    "rRV25",
    "rRVA",
    "rRVL",
    "rRVR05",
    "rRVR25",
    "sATMFlag",
    "sApiKey",
    "sApiKeyPassword",
    "sAzukariKin",
    "sBaDenpyouOutputUmuC",
    "sBadenpyouOutputYNC",
    "sBaiBaiDaikin",
    "sBaiBaiTesuryo",
    "sBaibaiKubun",
    "sBaibaiTani",
    "sBaibaiTaniYoku",
    "sBaibaiTeisiC",
    "sBankCode",
    "sBankName",
    "sBensaiKubun",
    "sBirthDay",
    "sBondUkewatasiDay",
    "sButenCode",
    "sCLMID",
    "sChannel",
    "sCheckOnly",
    "sCondition",
    "sConditionTeiseiFlg",
    "sCreateDate",
    "sCreateTime",
    "sDaiyoHosyokinRitu",
    "sDaiyouHyoukaTanka",
    "sDaiyouHyoukagaku",
    "sDate",
    "sDateTime",
    "sDayKey",
    "sDecimal_1",
    "sDecimal_10",
    "sDecimal_11",
    "sDecimal_12",
    "sDecimal_13",
    "sDecimal_14",
    "sDecimal_15",
    "sDecimal_16",
    "sDecimal_17",
    "sDecimal_18",
    "sDecimal_19",
    "sDecimal_2",
    "sDecimal_20",
    "sDecimal_3",
    "sDecimal_4",
    "sDecimal_5",
    "sDecimal_6",
    "sDecimal_7",
    "sDecimal_8",
    "sDecimal_9",
    "sDeleteDay",
    "sDeleteFlag",
    "sDeleteTime",
    "sEigyouDay",
    "sEigyouDayC",
    "sErrReasonCode",
    "sErrReasonText",
    "sEventName",
    "sFurikaeKouzaKubun",
    "sFusokugaku",
    "sGaikokuKouzaKubun",
    "sGaisanDaikin",
    "sGenbikiKanougaku",
    "sGenbikiWatasiHosyoukin",
    "sGenbikiWatasiTateDaikin",
    "sGenbutuBaibaiDaikin",
    "sGenbutuKabuKaituke",
    "sGenbutuKaituke",
    "sGenbutuKaitukeKanougaku",
    "sGenbutuKaitukeYoku",
    "sGenbutuOrderCount",
    "sGenbutuUrituke",
    "sGenbutuUritukeYoku",
    "sGenbutuYakuzyouCount",
    "sGenbutuZyoutoekiKazeiC",
    "sGenbwGenkinHosyoukin",
    "sGengetu",
    "sGenkinHosyokinRitu",
    "sGenkinHosyoukin",
    "sGenkinHosyoukinYoryoku",
    "sGenkinShinyouKubun",
    "sGenkinSinyouKubun",
    "sGensisanCode",
    "sGensisanKubun",
    "sGyakusasiKubun",
    "sGyakusasiOrderType",
    "sGyakusasiPrice",
    "sGyakusasiPriceKubun",
    "sGyakusasiPriceTeiseiFlg",
    "sGyakusasiZyouken",
    "sGyakusasiZyoukenTeiseiFlg",
    "sGyoumuZyoutai",
    "sGyousyuCode",
    "sGyousyuName",
    "sHakkouKaisiDay",
    "sHakkouSaisyuDay",
    "sHattyuDaiyouHyoukagaku",
    "sHattyuGenkinHosyoukin",
    "sHattyuHosyoukin",
    "sHattyuTateDaikin",
    "sHattyuZyutoukin",
    "sHenkouDay",
    "sHibakariKousokukin",
    "sHibuGyakuhibuKousokukin",
    "sHibuGyakuhibuSyueki",
    "sHikazeiC",
    "sHikazeiKouzaKaituke",
    "sHikazeiKouzaKubun",
    "sHikazeiTekiyouYear",
    "sHituke",
    "sHitukeIndex",
    "sHituyouGenkinHosyoukin",
    "sHituyouHosyoukin",
    "sHogoAdukariKouzaKubun",
    "sHonsitenCode",
    "sHonsitenName",
    "sHosyokinDaiyoKakeme",
    "sHosyouKinritu",
    "sHosyoukin",
    "sHosyoukinDaiyouKakeme",
    "sHosyoukinGenbutuKaitukeKanougaku",
    "sHosyoukinHikidasiKousokukin",
    "sHosyoukinHikidasiYoryoku",
    "sHosyoukinIziRitu",
    "sHosyoukinIzirituIziYoryoku",
    "sHosyoukinRitu",
    "sHosyoukinRituIziYoryoku",
    "sHosyoukinTyousyuRitu",
    "sHosyoukinYoryoku",
    "sHshzGenkinHosyoukin",
    "sHshzGenkinHosyoukinHasseiDay",
    "sHshzHosyoukin",
    "sHshzHosyoukinHasseiDay",
    "sHshzNyukinKigenDay",
    "sHusokukinHasseiFlg",
    "sHyoukaSonEki",
    "sHyoukaSonekiGoukeiKaidate",
    "sHyoukaSonekiGoukeiUridate",
    "sIPOKounyu",
    "sInsiderAgreement",
    "sIppanGaisanHyoukaSonekiGoukei",
    "sIppanGaisanHyoukagakuGoukei",
    "sIppanHyoukaSonekiGoukei",
    "sIppanSinyouGenbiki",
    "sIppanSinyouGenbikiYoku",
    "sIppanSinyouGenwatasi",
    "sIppanSinyouGenwatasiYoku",
    "sIppanSinyouKaiHensai",
    "sIppanSinyouKaiHensaiYoku",
    "sIppanSinyouSinkiKaitate",
    "sIppanSinyouSinkiKaitateYoku",
    "sIppanSinyouSinkiUritate",
    "sIppanSinyouSinkiUritateYoku",
    "sIppanSinyouUriHensai",
    "sIppanSinyouUriHensaiYoku",
    "sIssueBubetuC",
    "sIssueCode",
    "sIssueKisei1C",
    "sIssueKisei2C",
    "sIssueKubunC",
    "sIssueName",
    "sIssueNameEizi",
    "sIssueNameKana",
    "sIssueNameRyaku",
    "sItakuHosyoukinRitu",
    "sItakuhosyoukin",
    "sJsonOfmt",
    "sKabuKariUkewatasiDay",
    "sKabuUkewatasiDay",
    "sKaiHensai",
    "sKaiHensaiYoku",
    "sKaitate",
    "sKaitateDaikin",
    "sKaitateYoku",
    "sKarauriHugou",
    "sKarikessaiC",
    "sKawaseKouzaKubun",
    "sKenrikousiLastDay",
    "sKenriotiFlag",
    "sKenritukiSaisyuDay",
    "sKessaiGyakuhibu",
    "sKessaiKakikaeryou",
    "sKessaiKanrihi",
    "sKessaiKasikaburyou",
    "sKessaiOrderSuryo",
    "sKessaiSoneki",
    "sKessaiSonota",
    "sKessaiTateTesuryou",
    "sKessaiTatebiZyuni",
    "sKessaiTategyokuDay",
    "sKessaiTategyokuPrice",
    "sKessaiTotalSiteibi",
    "sKessaiTotalToday",
    "sKessaiWarningCode",
    "sKessaiWarningText",
    "sKessaiYakuzyouPrice",
    "sKessaiYakuzyouSuryo",
    "sKessaiZyunHibu",
    "sKessanC",
    "sKessanDay",
    "sKikoSankaC",
    "sKinri",
    "sKinsyouhouMidokuFlg",
    "sKizunPrice_1",
    "sKizunPrice_10",
    "sKizunPrice_11",
    "sKizunPrice_12",
    "sKizunPrice_13",
    "sKizunPrice_14",
    "sKizunPrice_15",
    "sKizunPrice_16",
    "sKizunPrice_17",
    "sKizunPrice_18",
    "sKizunPrice_19",
    "sKizunPrice_2",
    "sKizunPrice_20",
    "sKizunPrice_3",
    "sKizunPrice_4",
    "sKizunPrice_5",
    "sKizunPrice_6",
    "sKizunPrice_7",
    "sKizunPrice_8",
    "sKizunPrice_9",
    "sKoKey",
    "sKouboPrice",
    "sKousiPrice",
    "sKouzaNameKana",
    "sKouzaNumber",
    "sKouzaType",
    "sLargeKaidateYoryoku",
    "sLargeUridateYoryoku",
    "sLastBaibaiDay",
    "sLastLoginDate",
    "sLoginKyokaKubun",
    "sMMFKouzaKubun",
    "sMRFKouzaKubun",
    "sMaeEigyouDay_1",
    "sMaeEigyouDay_2",
    "sMaeEigyouDay_3",
    "sMeisaiNumber",
    "sMeyasuTime",
    "sMikessaiGenkinHosyoukin",
    "sMikessaiTateDaikin",
    "sMiniKaidateYoryoku",
    "sMiniUridateYoryoku",
    "sMiukewatasiKessaiEki",
    "sMiukewatasiKessaiSon",
    "sMsgId",
    "sMukigenC",
    "sNearaiKubun",
    "sNehabaCheckKahiC",
    "sNehabaKigenDay",
    "sNehabaKiseiC",
    "sNehabaKiseiTi",
    "sNehabaMax",
    "sNehabaMin",
    "sNehabaSansyutuSizyouC",
    "sNehabaSizyouC",
    "sNiruiKizituC",
    "sNisaGaisanHyoukaSonekiGoukei",
    "sNisaGaisanHyoukagakuGoukei",
    "sNisaKaitukeKanougaku",
    "sNissyoukinKasikabuZan",
    "sNseityouGaisanHyoukaSonekiGoukei",
    "sNseityouGaisanHyoukagakuGoukei",
    "sNseityouTousiKanougaku",
    "sNyusatuDay",
    "sNyusatuKaizyoDay",
    "sOhzHasseiDay",
    "sOhzHosyoukinRitu",
    "sOhzHosyoukinZougen",
    "sOhzKakuteiFlg",
    "sOhzKessaisonNyukin",
    "sOhzMikaisyouKingaku",
    "sOhzMikaisyouKingakuFlg",
    "sOhzNyukin",
    "sOhzNyukinKigenDay",
    "sOhzOisyouKingaku",
    "sOhzTategyokuKessai",
    "sOhzsDaiyouHyoukagaku",
    "sOhzsGenkinHosyoukin",
    "sOhzsHyoukaSoneki",
    "sOhzsItakuHosyoukinRitu",
    "sOhzsKeisanDay",
    "sOhzsMiukeKessaiEki",
    "sOhzsMiukeKessaiSon",
    "sOhzsSasiireHosyoukin",
    "sOhzsSyokeihi",
    "sOhzsTatekabuDaikin",
    "sOhzsUkeireHosyoukin",
    "sOisyouHasseiFlg",
    "sOisyouHituyouHosyoukin",
    "sOisyouKakuteiFlg",
    "sOisyouYoryoku",
    "sOogutiKabusu",
    "sOogutiKingaku",
    "sOpBaibaiDaikin",
    "sOpKaidateYoryokyu",
    "sOpOrderCount",
    "sOpYakuzyouCount",
    "sOrderAcceptTime",
    "sOrderBaibaiKubun",
    "sOrderBensaiKubun",
    "sOrderCondition",
    "sOrderCorrectCancelKahiFlg",
    "sOrderCurrentSuryou",
    "sOrderDate",
    "sOrderExpireDay",
    "sOrderExpireDayLimit",
    "sOrderExpireDayTeiseiFlg",
    "sOrderGaisanHyoukaSoneki",
    "sOrderGaisanHyoukaSonekiRitu",
    "sOrderGenbikiGenwatasiKabusu",
    "sOrderGyakuhibu",
    "sOrderGyakusasiKubun",
    "sOrderGyakusasiOrderType",
    "sOrderGyakusasiPrice",
    "sOrderGyakusasiZyouken",
    "sOrderHensaiKanouSuryou",
    "sOrderHyoukaTanka",
    "sOrderInputMethod",
    "sOrderIssueCode",
    "sOrderKakikaeryou",
    "sOrderKanrihi",
    "sOrderKasikaburyou",
    "sOrderKurikosiOrderFlg",
    "sOrderNumber",
    "sOrderOrderDateTime",
    "sOrderOrderExpireDay",
    "sOrderOrderNumber",
    "sOrderOrderPrice",
    "sOrderOrderPriceKubun",
    "sOrderOrderSuryou",
    "sOrderPrice",
    "sOrderPriceKubun",
    "sOrderPriceTeiseiFlg",
    "sOrderSikkouDay",
    "sOrderSizyouC",
    "sOrderSonota",
    "sOrderStatus",
    "sOrderStatusCode",
    "sOrderSuryou",
    "sOrderSuryouTeiseiFlg",
    "sOrderSyouhizei",
    "sOrderSyoukaiStatus",
    "sOrderTateTesuryou",
    "sOrderTatebiType",
    "sOrderTategyokuDay",
    "sOrderTategyokuKizituDay",
    "sOrderTategyokuNumber",
    "sOrderTategyokuSuryou",
    "sOrderTategyokuTanka",
    "sOrderTesuryou",
    "sOrderTriggerType",
    "sOrderType",
    "sOrderUkewatasiKingaku",
    "sOrderUtidekiKbn",
    "sOrderWarningCode",
    "sOrderWarningText",
    "sOrderYakuzyouHensaiKabusu",
    "sOrderYakuzyouPrice",
    "sOrderYakuzyouStatus",
    "sOrderYakuzyouSuryo",
    "sOrderZougen",
    "sOrderZyoutoekiKazeiC",
    "sOrderZyunHibu",
    "sOyaKey",
    "sPageTime",
    "sPassword",
    "sPutCall",
    "sReason",
    "sResultCode",
    "sResultText",
    "sRuitouKaituke",
    "sSaiteiHituyouHosyoukin",
    "sSakOpSyouhin",
    "sSakiBaibaiDaikin",
    "sSakiOrderCount",
    "sSakiYakuzyouCount",
    "sSakopKouzaKubun",
    "sSasiireHosyoukin",
    "sSecondPassword",
    "sSecondPasswordCrypt",
    "sSecondPasswordOmit",
    "sSeidoSinyouGenbiki",
    "sSeidoSinyouGenbikiYoku",
    "sSeidoSinyouGenwatasi",
    "sSeidoSinyouGenwatasiYoku",
    "sSeidoSinyouKaiHensai",
    "sSeidoSinyouKaiHensaiYoku",
    "sSeidoSinyouSinkiKaitate",
    "sSeidoSinyouSinkiKaitateYoku",
    "sSeidoSinyouSinkiUritate",
    "sSeidoSinyouSinkiUritateYoku",
    "sSeidoSinyouUriHensai",
    "sSeidoSinyouUriHensaiYoku",
    "sSeityouTousiKanougaku",
    "sShouhizei",
    "sSikkouDay",
    "sSinkiTesuryou",
    "sSinkiZyouzyouDay",
    "sSinyouBaibaiDaikin",
    "sSinyouC",
    "sSinyouGenbiki",
    "sSinyouKouzaKubun",
    "sSinyouOrderCount",
    "sSinyouSinkidate",
    "sSinyouSinkidateKanougaku",
    "sSinyouSyutyuKubun",
    "sSinyouSyutyuKubunYoku",
    "sSinyouTadeSyoukeihi",
    "sSinyouTateHyoukaEki",
    "sSinyouTateHyoukaSon",
    "sSinyouYakuzyouCount",
    "sSinyouZyoutoekiKazeiC",
    "sSizyouC",
    "sSizyouErrorCode",
    "sSizyoubetuBaibaiTani",
    "sSizyoubetuBaibaiTaniYoku",
    "sSogoKouzaKubun",
    "sSokuzituNyukinC",
    "sSokuzituNyukinCYoku",
    "sSokuzituNyukinKiseiDate",
    "sSonotaKousokukin",
    "sSonotaTateSyokeihi",
    "sSorC",
    "sStkSessionId",
    "sSummaryGenkabuKaituke",
    "sSummaryNisaKaitukeKanougaku",
    "sSummaryNseityouTousiKanougaku",
    "sSummarySinyouSinkidate",
    "sSummaryUpdate",
    "sSyouhinType",
    "sSyoukokinFusokugaku",
    "sSystemC",
    "sSystemKouzaKubun",
    "sSystemStatus",
    "sSystemStatusKey",
    "sSyukkin",
    "sSyukkinIraiKingaku",
    "sSyukkinIraigaku1",
    "sSyukkinIraigaku2",
    "sSyukkinIraigaku3",
    "sSyukkinIraigaku4",
    "sSyukkinIraigaku5",
    "sSyukkinKanouDay1",
    "sSyukkinKanouDay2",
    "sSyukkinKanouDay3",
    "sSyukkinKanouDay4",
    "sSyukkinKanouDay5",
    "sSyukkinKanougaku",
    "sSyukkinKanougaku1",
    "sSyukkinKanougaku2",
    "sSyukkinKanougaku3",
    "sSyukkinKanougaku4",
    "sSyukkinKanougaku5",
    "sSyuzituOwarine",
    "sT0HyoukaSonEki",
    "sT0ItakuHosyoukinRitu",
    "sT0OisyouHituyouHosyoukin",
    "sT0OisyouYoryoku",
    "sT0SasiireHosyoukin",
    "sT0TateKabuDaikin",
    "sT0UkeireHosyoukin",
    "sT5HyoukaSonEki",
    "sT5ItakuHosyoukinRitu",
    "sT5OisyouHituyouHosyoukin",
    "sT5OisyouYoryoku",
    "sT5SasiireHosyoukin",
    "sT5TateKabuDaikin",
    "sT5UkeireHosyoukin",
    "sTaisyouGyoumu",
    "sTaniSuryou",
    "sTargetCLMID",
    "sTargetColumn",
    "sTargetIssueCode",
    "sTateKabuDaikin",
    "sTatebiType",
    "sTatebiZyuni",
    "sTategyokuDaikin",
    "sTategyokuNumber",
    "sTategyokuSuryou",
    "sTategyokuZyoutoekiKazeiC",
    "sTatekabuHyoukaSoneki",
    "sTatekabuSyoukeihi",
    "sTatekaekinHasseiFlg",
    "sTeisiKubun",
    "sTekiyouDay",
    "sText",
    "sTheDay",
    "sThzHibakariKousokukin",
    "sThzHituyouNyukingaku",
    "sThzHurikaegaku",
    "sThzKakuteiFlg",
    "sThzNyukinKigenDay",
    "sThzSeisangaku",
    "sToday",
    "sTokuteiF",
    "sTokuteiGaisanHyoukaSonekiGoukei",
    "sTokuteiGaisanHyoukagakuGoukei",
    "sTokuteiHaitouKouzaKubun",
    "sTokuteiHyoukaSonekiGoukei",
    "sTokuteiKanriKouzaKubun",
    "sTokuteiKouzaKubunGenbutu",
    "sTokuteiKouzaKubunSinyou",
    "sTokuteiKouzaKubunTousin",
    "sTorihikiStartDay",
    "sTotalDaikin",
    "sTotalGaisanHyoukaSonekiGoukei",
    "sTotalGaisanHyoukagakuGoukei",
    "sTotalHyoukaSonekiGoukei",
    "sTousinKaituke",
    "sTousinKaitukeKanougaku",
    "sTouzituKessaiEki",
    "sTouzituKessaiSon",
    "sTouzituKessaiZenHyouka",
    "sTriggerTime",
    "sTriggerType",
    "sTyukokufKouzaKubun",
    "sUkeireHosyoukin",
    "sUkewatasiDay",
    "sUkewatasiDay1",
    "sUkewatasiDay2",
    "sUkewatasiDay3",
    "sUkewatasiDay4",
    "sUkewatasiDay5",
    "sUkewatasiTategyokuEki",
    "sUkewatasiTategyokuSon",
    "sUnyouCategory",
    "sUnyouStatus",
    "sUnyouUnit",
    "sUpDownFlag",
    "sUpdateDate",
    "sUpdateNumber",
    "sUpdateTime",
    "sUriHensai",
    "sUriHensaiYoku",
    "sUriOrderGaisanBokaTanka",
    "sUriOrderGaisanHyoukaSoneki",
    "sUriOrderGaisanHyoukaSonekiRitu",
    "sUriOrderGaisanHyoukagaku",
    "sUriOrderHyoukaTanka",
    "sUriOrderIssueCode",
    "sUriOrderUritukeKanouSuryou",
    "sUriOrderWarningCode",
    "sUriOrderWarningText",
    "sUriOrderZanKabuSuryou",
    "sUriOrderZyoutoekiKazeiC",
    "sUritate",
    "sUritateDaikin",
    "sUritateYoku",
    "sUrlEvent",
    "sUrlEventWebSocket",
    "sUrlMaster",
    "sUrlPrice",
    "sUrlRequest",
    "sUserId",
    "sUtidekiKubun",
    "sWarningCode",
    "sWarningText",
    "sYakuzyouDate",
    "sYakuzyouPrice",
    "sYakuzyouSuryou",
    "sYakuzyouWarningCode",
    "sYakuzyouWarningText",
    "sYobineTaniNumber",
    "sYobineTaniNumberYoku",
    "sYobineTanka_1",
    "sYobineTanka_10",
    "sYobineTanka_11",
    "sYobineTanka_12",
    "sYobineTanka_13",
    "sYobineTanka_14",
    "sYobineTanka_15",
    "sYobineTanka_16",
    "sYobineTanka_17",
    "sYobineTanka_18",
    "sYobineTanka_19",
    "sYobineTanka_2",
    "sYobineTanka_20",
    "sYobineTanka_3",
    "sYobineTanka_4",
    "sYobineTanka_5",
    "sYobineTanka_6",
    "sYobineTanka_7",
    "sYobineTanka_8",
    "sYobineTanka_9",
    "sYokuEigyouDay_1",
    "sYokuEigyouDay_10",
    "sYokuEigyouDay_2",
    "sYokuEigyouDay_3",
    "sYokuEigyouDay_4",
    "sYokuEigyouDay_5",
    "sYokuEigyouDay_6",
    "sYokuEigyouDay_7",
    "sYokuEigyouDay_8",
    "sYokuEigyouDay_9",
    "sYusenSizyou",
    "sZanKabuSuryouUriKanouIppan",
    "sZanKabuSuryouUriKanouNisa",
    "sZanKabuSuryouUriKanouNseityou",
    "sZanKabuSuryouUriKanouTokutei",
    "sZenzituHi",
    "sZenzituHiPer",
    "sZenzituOwarine",
    "sZenzituRironPrice",
    "sZizenCyouseiC",
    "sZizenCyouseiCYoku",
    "sZougen",
    "sZyouhouCode",
    "sZyouhouSource",
    "sZyoutoekiKazeiC",
    "sZyouzyouHaisiDay",
    "sZyouzyouHakkouKabusu",
    "sZyouzyouKubun",
    "sZyouzyouNyusatuC",
    "sZyouzyouOutouDay",
    "sZyouzyouSizyou",
    "tDHP:T",
    "tDLP:T",
    "tDOP:T",
    "tDPP:T",
    "xDCFS",
    "xDVES",
    "xLISS",
];

/// Replace numeric string keys with column names.
///
/// Keys are 1-indexed: key `"334"` → `COLUMNS[333]` = `"sCLMID"`.
/// Non-numeric keys, out-of-range keys, and non-object values pass through unchanged.
/// Array elements are recursively uncompressed.
pub fn uncompress(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut out = Map::with_capacity(map.len());
            for (k, v) in map {
                let new_key = k
                    .parse::<usize>()
                    .ok()
                    .and_then(|n| n.checked_sub(1))
                    .and_then(|idx| COLUMNS.get(idx))
                    .map(|&col| col.to_string())
                    .unwrap_or_else(|| k.clone());
                out.insert(new_key, uncompress(v));
            }
            Value::Object(out)
        }
        Value::Array(arr) => Value::Array(arr.iter().map(uncompress).collect()),
        other => other.clone(),
    }
}

/// Replace column name keys with numeric string keys.
///
/// Uses binary search on `COLUMNS` (which is sorted alphabetically).
/// Column found at index `i` → key becomes `(i + 1).to_string()`.
/// Unknown keys pass through unchanged.
/// Array elements are recursively compressed.
pub fn compress(value: &Value) -> Value {
    match value {
        Value::Object(map) => {
            let mut out = Map::with_capacity(map.len());
            for (k, v) in map {
                let new_key = COLUMNS
                    .binary_search(&k.as_str())
                    .ok()
                    .map(|idx| (idx + 1).to_string())
                    .unwrap_or_else(|| k.clone());
                out.insert(new_key, compress(v));
            }
            Value::Object(out)
        }
        Value::Array(arr) => Value::Array(arr.iter().map(compress).collect()),
        other => other.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_columns_count() {
        assert_eq!(COLUMNS.len(), 941);
    }

    #[test]
    fn test_columns_sorted() {
        for pair in COLUMNS.windows(2) {
            assert!(
                pair[0] < pair[1],
                "COLUMNS not sorted: {:?} >= {:?}",
                pair[0],
                pair[1]
            );
        }
    }

    #[test]
    fn test_uncompress_basic() {
        // "sCLMID" is at index 333, key "334"
        // "sResultCode" is at index 687, key "688"
        let input = json!({"334": "CLMAuthLoginAck", "688": "0"});
        let expected = json!({"sCLMID": "CLMAuthLoginAck", "sResultCode": "0"});
        assert_eq!(uncompress(&input), expected);
    }

    #[test]
    fn test_compress_basic() {
        let input = json!({"sCLMID": "CLMAuthLoginAck", "sResultCode": "0"});
        let expected = json!({"334": "CLMAuthLoginAck", "688": "0"});
        assert_eq!(compress(&input), expected);
    }

    #[test]
    fn test_uncompress_with_array() {
        // "aOrderList" is at index 93, key "94"
        let input = json!({
            "334": "CLMOrderList",
            "94": [
                {"643": "ORD001", "657": "10"},
                {"643": "ORD002", "657": "1"}
            ]
        });
        let expected = json!({
            "sCLMID": "CLMOrderList",
            "aOrderList": [
                {"sOrderNumber": "ORD001", "sOrderStatusCode": "10"},
                {"sOrderNumber": "ORD002", "sOrderStatusCode": "1"}
            ]
        });
        assert_eq!(uncompress(&input), expected);
    }

    #[test]
    fn test_compress_with_array() {
        let input = json!({
            "sCLMID": "CLMOrderList",
            "aOrderList": [
                {"sOrderNumber": "ORD001", "sOrderStatusCode": "10"},
                {"sOrderNumber": "ORD002", "sOrderStatusCode": "1"}
            ]
        });
        let expected = json!({
            "334": "CLMOrderList",
            "94": [
                {"643": "ORD001", "657": "10"},
                {"643": "ORD002", "657": "1"}
            ]
        });
        assert_eq!(compress(&input), expected);
    }

    #[test]
    fn test_uncompress_mixed_keys() {
        // Mix of numeric keys (known), numeric keys (out of range), and non-numeric keys
        let input = json!({"334": "CLMAuthLoginAck", "custom_key": "value", "9999": "unknown"});
        let result = uncompress(&input);
        assert_eq!(result["sCLMID"], "CLMAuthLoginAck");
        assert_eq!(result["custom_key"], "value");
        // 9999 is out of COLUMNS range (only 941 items), so passes through
        assert_eq!(result["9999"], "unknown");
    }

    #[test]
    fn test_compress_mixed_keys() {
        let input = json!({"sCLMID": "CLMAuthLoginAck", "unknown_field": "value"});
        let result = compress(&input);
        assert_eq!(result["334"], "CLMAuthLoginAck");
        assert_eq!(result["unknown_field"], "value");
    }

    #[test]
    fn test_roundtrip_uncompress_compress() {
        let compressed = json!({
            "334": "CLMAuthLoginAck",
            "688": "0",
            "689": "OK",
            "288": "1",
            "290": "2026.03.21-10:00:00.000"
        });
        assert_eq!(compress(&uncompress(&compressed)), compressed);
    }

    #[test]
    fn test_roundtrip_compress_uncompress() {
        let readable = json!({
            "sCLMID": "CLMAuthLoginAck",
            "sResultCode": "0",
            "sResultText": "OK",
            "p_no": "1",
            "p_sd_date": "2026.03.21-10:00:00.000"
        });
        assert_eq!(uncompress(&compress(&readable)), readable);
    }

    #[test]
    fn test_non_object_passthrough() {
        assert_eq!(uncompress(&json!("hello")), json!("hello"));
        assert_eq!(uncompress(&json!(42)), json!(42));
        assert_eq!(uncompress(&json!(null)), json!(null));
        assert_eq!(compress(&json!("hello")), json!("hello"));
        assert_eq!(compress(&json!(42)), json!(42));
    }

    #[test]
    fn test_key_zero_passthrough() {
        // Key "0" is invalid (1-indexed), should pass through
        let input = json!({"0": "value"});
        assert_eq!(uncompress(&input), json!({"0": "value"}));
    }

    #[test]
    fn test_specific_column_indices() {
        // Verify a few known column positions
        assert_eq!(COLUMNS[0], "CLMAuthApiKeyEncryptAck"); // key "1"
        assert_eq!(COLUMNS[333], "sCLMID"); // key "334"
        assert_eq!(COLUMNS[687], "sResultCode"); // key "688"
        assert_eq!(COLUMNS[688], "sResultText"); // key "689"
        assert_eq!(COLUMNS[940], "xLISS"); // key "941"
    }
}
